<a href="https://colab.research.google.com/github/SiriusBits/ml-engineering-lab/blob/main/LA2_Assignment_Solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
A=np.array([[2,3,4],[2,3,4],[4,5,6]])

##Write a Python function that takes a matrix A and an integer k as input and returns the top k principal components of A using PCA.

In [ ]:
import numpy as np

def pca(A, k):
    eigen_vals, eigen_vecs = eigen_decomp(np.cov(A.T))
    idx = eigen_vals.argsort()[::-1]
    eigen_vals = eigen_vals[idx]
    eigen_vecs = eigen_vecs[:,idx]
    principal_components = eigen_vecs[:, :k]
    transformed = A.dot(principal_components)
    return transformed

In [ ]:
pca(A, 2)

array([[-5.19615242,  1.40824829],
       [-5.19615242,  1.40824829],
       [-8.66025404,  1.40824829]])

##Write a Python function that takes a matrix A as input and returns its singular value decomposition (SVD).

In [ ]:
#Solution-1

In [ ]:
import numpy as np

def svd_decomp(A):
    U, Sigma, Vt = np.linalg.svd(A)
    return U, Sigma, Vt

In [ ]:
svd_decomp(A)

(array([[-4.63279613e-01, -5.34202209e-01, -7.07106781e-01],
        [-4.63279613e-01, -5.34202209e-01,  7.07106781e-01],
        [-7.55476009e-01,  6.55176312e-01, -1.16573418e-15]]),
 array([1.16035987e+01, 5.97073667e-01, 5.69821139e-16]),
 array([[-0.42013022, -0.56508829, -0.71004635],
        [ 0.81044675,  0.11835777, -0.57373122],
        [-0.40824829,  0.81649658, -0.40824829]]))



##Write a python code to derive simple linear regressions best fit line in python

In [ ]:
#Solution-1

In [ ]:
def simple_linear_regression(X,Y,L=0.015,epochs=1000):
  # Building the model
  m = 0
  c = 0
  n = float(len(X)) # Number of elements in X

  # Performing Gradient Descent
  for i in range(epochs):
      Y_pred = m*X + c  # The current predicted value of Y
      D_m = (-2/n) * sum(X * (Y - Y_pred))  # Derivative wrt m
      D_c = (-2/n) * sum(Y - Y_pred)  # Derivative wrt c
      m = m - L * D_m  # Update m
      c = c - L * D_c  # Update c
  print("Intercept (c):", c)
  print("Slope (m):", m)

  return m,c

X = np.array([1, 2, 3, 4, 5])
Y = np.array([2, 4, 5, 4, 5])
simple_linear_regression(X,Y,L=0.015,epochs=1000)

Intercept (c): 2.1883022102284166
Slope (m): 0.6032401001920664


(0.6032401001920664, 2.1883022102284166)

In [ ]:
#Solution-2

In [ ]:
import numpy as np

def simple_linear_regression(x, y):
    n = len(x)
    x_mean = np.mean(x)
    y_mean = np.mean(y)

    # Calculate the slope (beta_1) and intercept (beta_0)
    beta_1 = sum((x_i - x_mean)*(y_i - y_mean) for x_i, y_i in zip(x,y))/sum((x_i - x_mean)**2 for x_i in x)
    beta_0 = y_mean - beta_1*x_mean

    return beta_0, beta_1

# Example usage
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 4, 5])
beta_0, beta_1 = simple_linear_regression(x, y)
print("Intercept (beta_0):", beta_0)
print("Slope (beta_1):", beta_1)


0.6032401001920664 2.1883022102284166
