<a href="https://colab.research.google.com/github/SiriusBits/ml-engineering-lab/blob/main/notebooks/LA/Pre_Class_Notebook_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# VECTORS

**Objectives**:
- Understand the concept of vectors and their properties.
- Perform vector operations such as addition, subtraction, and scalar multiplication.
- Calculate the magnitude and direction of a vector.
- Understand the concept of linear combinations and linear independence

#1.1 Definition of vectors
A Vector in Python is simply a one-dimensional array of lists.

We use numpy.array() method to create vector

In [ ]:
import numpy as np
myList = [1, 2, 3]
myVector = np.array(myList)

print("Let's see what our vector looks like: ")
print(myVector)

Let's see what our vector looks like: 
[1 2 3]


Vectors can be horizontal or vertical. In the next code block, you can see the difference between the appearance of these vectors



In [ ]:
myVector.shape

(3,)

In [ ]:
np.arange(100).reshape(-1,4).shape

(25, 4)

In [ ]:
myVector.reshape(-1,3)

array([[1, 2, 3]])

In [ ]:
horizontalVector = np.array([1, 2, 3, 4])
verticalVector = np.array([[1],[2],[3],[4]])

print("Horizontal Vector created from list: ")
print(horizontalVector)
print()

print("Vertical Vector created from list: ")
print(verticalVector)

Horizontal Vector created from list: 
[1 2 3 4]

Vertical Vector created from list: 
[[1]
 [2]
 [3]
 [4]]



#1.2 Vector operations



Numpy arrays (vectors) can be operated upon by the following operations. Some of these operations are:
 - Addition
 - Subtraction
 - Multiplication
 - Division
 - Dot Product

#### Addition
The addition operation takes place in an element-wise manner i.e. element by element. As a result, the resultant vector would have the same length as that of the two additive vectors

In [ ]:
# Addition
vec1 = np.array([10,20,30,40,50])
vec2 = np.array([1,2,3,4,5])
sum = vec1+vec2
print(sum)

[11 22 33 44 55]


#### Subtraction
Similarly, the element-wise fashion would be followed in subtraction as well. The elements of vector 2 will get subtracted from vector 1.


In [ ]:
# Subtraction
vec1 = np.array([10,20,30,40,50])
vec2 = np.array([1,2,3,4,5])
sub = vec1-vec2
print(sub)

[ 9 18 27 36 45]


#### Multiplication
In a vector multiplication, the elements of vector 1 get multiplied by the elements of vector 2 in an element-wise manner and the product vector is of the same length as of the multiplying vectors.
In the code block below, for example, we can see that

**mul[0] = vec1[0] * vec2[0]**

**mul[1] = vec1[1] * vec2[1]**

and so on...


In [ ]:
# Multiplication

vec1 = np.array([10,20,30,40,50])
vec2 = np.array([1,2,3,4,5])
# Vectors must be on the same dimension
#vec3 = np.array([2, 4])
mul =  vec1*vec2 # * --> Dot product for vectors
#mul = vec1 * vec3
print(mul)

[ 10  40  90 160 250]


#### Division
Similar to vector multiplication, in vector division, the resultant vector is the quotient values after carrying out element-by-element division operation on the two vectors
In the code block below, for example, we can see that

**div[0] = vec1[0] / vec2[0]**

**div[1] = vec1[1] / vec2[1]**

and so on...


In [ ]:
# Division
vec1 = np.array([10,20,30,40,50])
vec2 = np.array([1,4,4,4,5])
div = vec1/vec2 # --> Elemenwise division
print(div)

[10.   5.   7.5 10.  10. ]


#### Operations with Scalers
All the mentioned operations can be done using scalers too. In that case, the scaler will be iterated over all the elements of the vector

In [ ]:
# Operations using Scaler
vec = np.array([1,2,3,4,5])
scaler = 5

print(scaler*vec)

[ 5 10 15 20 25]


#### Vector Dot Product
In a vector dot product, we perform the summation of the product of the two vectors in an element-wise fashion. As a result, the resultant is not a vector, but a scalar value


In [ ]:
# Vector Dot Product
vec1 = np.array([1,3,5,7,9])
vec2 = np.array([1,1,1,1,1])
usualdp = (vec1 * vec2)
dotProduct = vec1.dot(vec2)
print(usualdp,dotProduct)

[1 3 5 7 9] 25


#### Vector Cross Product

In [ ]:
# Vector Cross Product
vec1 = np.array([0, 2, 0])
vec2 = np.array([0, 0, 3])
mul =  np.cross(vec1, vec2)
print(mul)

[6 0 0]


# 1.3 Magnitude and direction

The magnitude of a vector is the square root of sum of element-wise squares of values in the vector. A simple way to find this would be to take the square root of the dot product of a vector with itself.

In [ ]:
# Magnitude of Vector
from math import sqrt
vec = np.array([3,4])
dotProd = vec.dot(vec)
magnitude = sqrt(dotProd)

print(f"Magnitude of the vector: {vec} is {magnitude}")

Magnitude of the vector: [3 4] is 5.0


In [ ]:
# Unit Vector --> Length 1
# Direction is typically computed for the Unit Vector.


# Given a Vector, you want a compute the unit vector --> Just divide the vector by the magnitude of the vector

A unit vector in the direction of the vector can be found out by dividing the vector by the magnitude of the vector.

In [ ]:
# direction of the vector
vec = np.array([3,4])
magnitude = sqrt(vec.dot(vec))

unitVec = vec/magnitude
print(f"Unit vector in the direction of the vector: {vec} is {unitVec}")

Unit vector in the direction of the vector: [3 4] is [0.6 0.8]


In [ ]:
vec1 = np.array([0, 2, 5])
vec2 = np.array([0, 0, 3])

def vector_add(u,v):
  m_vec1 = np.sqrt((vec1 * vec1).sum())
  m_vec2 = np.sqrt((vec2 * vec2).sum())
  cos_theta = (vec1 * vec2).sum()/(m_vec1 * m_vec2)

  return np.sqrt(m_vec1 ** 2 + m_vec2 ** 2 + 2 * m_vec1 * m_vec2 * cos_theta)


vector_add(vec1,vec2)

8.246211251235321

# 1.4 Linear combinations and linear independence

A linear combination of two (or more) vectors is the vector obtained by adding the vectors after multiplying them by scalar values.

In [ ]:
# Linear Combinations
vec1 = np.array([1,2])
vec2 = np.array([3,1])

s1 = int(input("Input the scaler with which to multiply the first vector: "))
s2 = int(input("Input the scaler with which to multiply the second vector: "))

resultant = vec1*s1 + vec2*s2
# z-axle (x, y, 0) -> (a, b, c)
print(f"{vec1} * {s1} + {vec2} * {s2} = {resultant}")

Input the scaler with which to multiply the first vector: -100
Input the scaler with which to multiply the second vector: -5
[1 2] * -100 + [3 1] * -5 = [-115 -205]


2. Linear Independence:
Let's consider two vectors a = (1, 3) and b = (2, 6). To check if these vectors are linearly dependent, we need to see if there are any non-zero scalars x and y such that:
x * a + y * b = 0
Let's try to find such scalars:
x * (1, 3) + y * (2, 6) = (0, 0)
(1x + 2y, 3x + 6y) = (0, 0)
From the first component, we have:
1x + 2y = 0 => x = -2y
From the second component, we have:
3x + 6y = 0
Substituting x = -2y, we get:
3(-2y) + 6y = 0 => -6y + 6y = 0
Since the equation is true for any value of y, we can choose y = 1, which gives us x = -2. Therefore, we have: -2 * (1, 3) + 1 * (2, 6) = (0, 0)

Refer to this link for more examples: https://www.statlect.com/matrix-algebra/linear-independence

In [ ]:
import numpy as np

np.linalg.matrix_rank([[1,2,1],[-2,-3,1],[3,5,0]])


2

In [ ]:
np.linalg.det([[1,2,1],[-2,-3,1],[3,5,0]])

1.3322676295501906e-15

In [ ]:
from numpy.linalg import eig

a = np.array([[0, 2],
              [2, 3]])
w,v=eig(a)
print('E-value:', w)
print('E-vector', v)


E-value: [-1.  4.]
E-vector [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


In [ ]:
a = np.array([[2, 2, 4],
              [1, 3, 5],
              [2, 3, 4]])
w,v=eig(a)
print('E-value:', w)
print('E-vector', v)

E-value: [ 8.80916362  0.92620912 -0.73537273]
E-vector [[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]


In [ ]:
np.linalg.inv([[1,2,1],[-2,-3,1],[3,5,0]])

array([[-3.75299969e+15,  3.75299969e+15,  3.75299969e+15],
       [ 2.25179981e+15, -2.25179981e+15, -2.25179981e+15],
       [-7.50599938e+14,  7.50599938e+14,  7.50599938e+14]])

In [ ]:
np.linalg.det([[1,2,1],[-2,-3,1],[3,5,0]])

1.3322676295501906e-15

In [ ]:
1.08512512585217512752195129521951291291259125921591259125129

1.085125125852175

In [ ]:
np.linalg.inv([[1,2],[2,4]])

LinAlgError: ignored

In [ ]:
np.linalg.pinv([[1,2],[2,4]])

array([[0.04, 0.08],
       [0.08, 0.16]])